// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


var Location = /* module */[];

var Action = /* module */[];

exports.Location = Location;
exports.Action = Action;
/* No side effect */
